# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attacks.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 858)
        MainWindow.setStyleSheet("color: rgb(170, 0, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 230, 431, 81))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    font: 16pt \"Arial Rounded MT Bold\";\n"
"    background-color:rgb(0, 0, 47);\n"
"    color: rgb(255, 65, 20);\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 40px;\n"
"    border-color:rgb(200, 66, 0) ;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 160, 52);\n"
"    color: rgb(16, 16, 16);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 670, 431, 81))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    font: 16pt \"Arial Rounded MT Bold\";\n"
"    background-color:rgb(0, 0, 47);\n"
"    color: rgb(255, 65, 20);\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 40px;\n"
"    border-color:rgb(200, 66, 0) ;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 160, 52);\n"
"    color: rgb(16, 16, 16);\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 340, 431, 81))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    font: 16pt \"Arial Rounded MT Bold\";\n"
"    background-color:rgb(0, 0, 47);\n"
"    color: rgb(255, 65, 20);\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 40px;\n"
"    border-color:rgb(200, 66, 0) ;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 160, 52);\n"
"    color: rgb(16, 16, 16);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 450, 431, 81))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    font: 16pt \"Arial Rounded MT Bold\";\n"
"    background-color:rgb(0, 0, 47);\n"
"    color: rgb(255, 65, 20);\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 40px;\n"
"    border-color:rgb(200, 66, 0) ;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 160, 52);\n"
"    color: rgb(16, 16, 16);\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(450, 560, 431, 81))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    font: 16pt \"Arial Rounded MT Bold\";\n"
"    background-color:rgb(0, 0, 47);\n"
"    color: rgb(255, 65, 20);\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 40px;\n"
"    border-color:rgb(200, 66, 0) ;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(255, 160, 52);\n"
"    color: rgb(16, 16, 16);\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 1191, 141))
        self.label.setStyleSheet("QLabel {\n"
"color:rgb(164, 74, 74);\n"
"border: 8px solid rgb(24, 103, 155);\n"
"border-color:rgb(255, 201, 142);\n"
"    font: 70 18pt \"Rockwell\";\n"
"border-radius: 80px;\n"
"background-color:rgb(128, 238, 255);\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-30, -40, 1920, 1080))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("earth.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton_5.raise_()
        self.pushButton_4.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DDOS  Attacks analysis using machine learning techniques"))
        self.pushButton_2.setText(_translate("MainWindow", "Dataset Columns Filtering"))
        self.pushButton_5.setText(_translate("MainWindow", "Heat Map Generation"))
        self.pushButton_4.setText(_translate("MainWindow", "Gaussian Naive Bayes Analysis"))
        self.pushButton_6.setText(_translate("MainWindow", "Adaboost Analysis"))
        self.pushButton_7.setText(_translate("MainWindow", "Comparison Plot"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; text-decoration: underline; color:#00003d;\">Detection and Characterization of </span></p><p align=\"center\"><span style=\" font-weight:600; text-decoration: underline; color:#00003d;\">DDoS Attacks Using Time-Based Features</span></p></body></html>"))
